summit_xl_controller:
  diameter_wheel: 0.254 # 0.220 for rubber wheels and 0.254 for omni wheels
  gearbox_reduction: 9.56
  kinematic_mode: "omni"
  motion_odometry: "false"
  motors_encoder: "true"
  motors_encoder_factor: 4000
  take-over: false
  x_wam: "true"
  xwam: 'true'
  imu_source: 'imu'
  yaw_topic: 'imu/data'
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# If motors_encoders == true motors speed is multiplied by motors_encoder_factor
# If no encoders it MUST be false
# Robot will increase his speed DANGEROUSLY if true with no encoders
#
# Gearbox (normally 12.52 or 9.56)
#
# Kinematic mode is "skid" or "omni"


