<?xml version="1.0"?>
<robot name="summit_x" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

	<xacro:include filename="$(find summit_x_description)/urdf/bases/summit_x_base.gazebo.xacro" />
  
  <macro name="box_inertia" params="m x y z">
		<inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
			iyy="${m*(x*x+z*z)/12}" iyz = "0"
			izz="${m*(x*x+z*z)/12}"
		/>
	</macro>
  
	<xacro:macro name="summit_x_base" params="name publish_bf">

	<!-- Robot mechanical and motor parameters -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	<xacro:property name="wheel_width" value="0.175" />
  

	<!-- BASE FOOTPRINT -->
	<xacro:if value="${publish_bf}">
		<link name="base_footprint">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</visual>
		</link>

		<joint name="base_footprint_joint" type="fixed">
			<origin xyz="0 0 ${2*wheel_radius}" rpy="0 0 0" /> <!-- ${wheel_radius} property must be defined inside wheel description -->
			<parent link="base_footprint"/>
			<child link="base_link" />
		</joint>    
  </xacro:if>


  <!-- BASE_LINK -->
	<link name="base_link">
		<inertial>
			<mass value="25.0" />
			<origin xyz="0 0 0" />
			<inertia  ixx="1.391" ixy="0.004"  ixz="0.0"  iyy="6.853"  iyz="0.0"  izz="6.125" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://summit_x_description/meshes/bases/chassis_xwam_down.stl"/>
			</geometry>
			<material name="summit_x_base_color">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>  
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
				<geometry>
					<mesh filename="package://summit_x_description/meshes/bases/chassis_xwam_down.stl"/>
				</geometry>
		</collision>     
	</link>
	
	<!-- ***************************** --> 
  <!-- ROVER PART - UP SCISSOR MECH  --> 
  <!-- ***************************** --> 
	<link name="rover_link">
		<inertial>
			<mass value="1.0" /> <!-- 20.0 -->
			<origin xyz="0 0 0" />
			<inertia  ixx="0.2185" ixy="0.0"  ixz="-0.001"  iyy="0.33677"  iyz="0.0"  izz="0.20511" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://summit_x_description/meshes/bases/chassis_xwam_up.stl"/>
			</geometry>
			<material name="summit_x_rover_color">
				<color rgba="0.1 0.1 0.1 1"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
			<geometry>
				<mesh filename="package://summit_x_description/meshes/bases/chassis_xwam_up.stl"/>
			</geometry>
		</collision>     
	</link>

  <joint name="scissor_prismatic_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="rover_link"/>
    <limit effort="100000.0" velocity="1000.0" lower="0.0" upper="0.5"/> <!-- lower="0.1" upper="0.5" -->
    <origin rpy="0 0 0" xyz="0.261 0 -0.038"/>
    <axis xyz="0 0 1"/>
  </joint>

  <transmission name="joint_scissor_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="scissor_prismatic_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="scissor_motor">
      <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>



  
<!--
	<joint name="camera_joint" type="fixed">
			<axis xyz="0 1 0" />
			<origin xyz="0.0 0.0 0.13" rpy="0.0 ${PI/4} 0.0"/>
      <parent link="rover_link"/>
      <child link="camera_link"/>
  </joint>
	
	<link name="camera_link">
		<inertial>
			<origin xyz="0.03 0.0 -0.3" rpy="0 0 0"/>
			<mass value="0.1" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
		</inertial>
	</link>
-->
  

  <!-- Axis camera properties-->
<!--
	<xacro:property name="ptz_joint_effort_limit" value="100.0" /> 
  <xacro:property name="ptz_joint_velocity_limit" value="100.0"/>  
  <xacro:property name="ptz_joint_friction" value="0.1" />
  <xacro:property name="ptz_joint_damping" value="0.1" />
  <xacro:property name="ptz_mechanical_reduction" value="1.0" />
-->

<!--
  <joint name="joint_camera_pan" type="continuous">
     <axis xyz="0 0 1" />
     <origin xyz="0.0 0.0 0.1"/>
     <parent link="camera_link"/>
     <child link="camera_pan_link"/>
     <limit effort="${ptz_joint_effort_limit}" velocity="${ptz_joint_velocity_limit}" lower="-3.1416" upper="3.1416"/>
     <joint_properties damping="${ptz_joint_damping}" friction="{ptz_joint_friction}"/>
  </joint>  
  
  <link name="camera_pan_link">
     <inertial>
       <mass value="0.1" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
  </link>
  
  <transmission name="camera_pan_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="joint_camera_pan" />
     <actuator name="pan_motor">
		   <hardwareInterface>EffortJointInterface</hardwareInterface>
       <mechanicalReduction>${ptz_mechanical_reduction}</mechanicalReduction>
     </actuator>
  </transmission>


  <joint name="joint_camera_tilt" type="continuous">
     <axis xyz="0 1 0" />
     <origin xyz="0.0 0.0 0.0"/>
     <parent link="camera_pan_link"/>
     <child link="camera_tilt_link"/>
     <limit effort="${ptz_joint_effort_limit}" velocity="${ptz_joint_velocity_limit}" lower="-1.5708" upper="1.5708"/>
     <joint_properties damping="${ptz_joint_damping}" friction="{ptz_joint_friction}"/>
  </joint>
  
  <link name="camera_tilt_link">
     <inertial>
       <mass value="0.1" />
       <origin xyz="0 0 0" rpy="0 0 0" />
       <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
  </link>
  
  <transmission name="camera_tilt_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="joint_camera_tilt" />
     <actuator name="tilt_motor">
			 <hardwareInterface>EffortJointInterface</hardwareInterface>
			 <mechanicalReduction>${ptz_mechanical_reduction}</mechanicalReduction>
     </actuator>
  </transmission>
-->






	<!-- Hokuyo sensor -->
	<joint name="hokuyo_laser_joint" type="fixed">
		<origin xyz="0.075 0.0 0.0" rpy="${PI} 0 0"/>
		<parent link="rover_link"/>
		<child link="hokuyo_laser_link"/>
	</joint>

	<link name="hokuyo_laser_link">
		<inertial>
			<mass value="1e-5" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>


	</xacro:macro>
</robot>

