joint_blw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

joint_brw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

joint_frw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

joint_flw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

joint_front_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: camera_front_pan_joint
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
joint_front_tilt_position_controller:
    type: position_controllers/JointPositionController
    joint: camera_front_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 50.0}

joint_rear_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: camera_rear_pan_joint
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
joint_rear_tilt_position_controller:
    type: position_controllers/JointPositionController
    joint: camera_rear_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 50.0}

joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
